### ISSUE TITLE
53c9a0f6216 breaks when current commit == tag

### ISSUE THREAD

**Issue by hyperthunk** [esl/edown#20]
This code breaks when you've _just_ made a tag and the git command returns the tag-name instead of the commit sha!

``` erlang
get_git_branch() ->
    Git = os:cmd("git describe --always --all"),   %% returns v0.7.8 when that's the current commit!
    case string:tokens(Git, " \n/") of
        [_, Branch] -> Branch;
        Other       -> erlang:error({cannot_get_git_branch, Other})
    end.
```

**Comment by uwiger** [comment]
Thanks. I just pushed an update to master, where the fallback for get_git_branch() becomes "master".

**Comment by uwiger** [comment]
closing - reopen issue if still a problem.
