### ISSUE TITLE
R16(A) support

### ISSUE THREAD

**Issue by norton** [esl/edown#24]
edown fails to compile with R16(A).

suggestions on how or if you want to fix this?

==> edown (compile)
./make_doc
Making edown docs for [http://github.com/esl/edown]...
edoc: error in doclet 'edown_doclet': {'EXIT',{undef,[{packages,strip_last,[edown_xmerl],[]},{edown_doclet,check_name,4,[{file,[115,114,99,47,101,100|...]},{line,301}]},{edown_doclet,source,9,[{file,[115,114,99,47,101|...]},{line,284}]},{lists,foldl,3,[{file,[108,105,115,116|...]},{line,1248}]},{edown_doclet,sources,5,[{file,[115,114,99|...]},{line,267}]},{edown_doclet,gen,6,[{file,[115,114|...]},{line,133}]},{edoc_lib,run_plugin,5,[{file,[101|...]},{line,1029}]},{erl_eval,do_apply,6,[{file,[...]},{line,...}]}]}}.
escript: exception exit: error

**Comment by jeremyong** [comment]
Same issue confirmed in R16B

**Comment by uwiger** [comment]
Edown has no use for packages, so this should be easy to fix. Unfortunately, I haven't had time to look into it. Pull requests are most welcome. Please consider pull request 23 as well, as it looks very promising (I just haven't had time to verify it).

**Comment by uwiger** [comment]
Try the latest push

https://github.com/esl/edown/commit/3d62a7795b6f052aef51faca474c3c45a291aa65

**Comment by uwiger** [comment]
Anyone still seeing problems with R16A?

**Comment by norton** [comment]
R16B is working for me now.

**Comment by uwiger** [comment]
ok, closing.
