### ISSUE TITLE
Markdown contains `<br></br>`

### ISSUE THREAD

**Issue by jtmoulia** [esl/edown#29]
Hey, generating markdown with edown produces `<br></br>` elements, valid XML, but not valid HTML. When converting the markdown to HTML and viewing in the browser the opening `<br>` is correctly rendered as a line break, but the closing `</br>` tag is being escaped (see below). I'm using [kramdown](http://kramdown.gettalong.org/) with [jekyll](http://jekyllrb.com/) to generate the html. It would be nice if kramdown didn't escape the `</br>` closing tag, but since it isn't valid I suppoose they're justified.

Is generating both an opening and closing tag for `<br>` an issue with `xmerl`?

Below is the markdown and HTML produced:
#### Markdown:

``` markdown
<br></br>
```
#### HTML:

``` html
<p><br />&lt;/br&gt;</p>
```

Thanks!

**Comment by uwiger** [comment]
Could you try PR #30 and let me know if it solves your problem?

**Comment by jtmoulia** [comment]
Perfect -- thanks for the fix, and all your great work.

**Comment by uwiger** [comment]
Ok. I've merged into master.
