### ISSUE TITLE
Escaping of angle brackets

### ISSUE THREAD

**Issue by si14** [esl/edown#5]
Github's MD parser don't handle angle brackets in text properly, so they should be replaced with &lt; &gt;.

**Comment by uwiger** [comment]
Do you have an example?

**Comment by si14** [comment]
Yeah, it is the documentation for http://github.com/siberian-fast-food/alogger . Look here https://github.com/siberian-fast-food/alogger/blob/master/doc/alog_control.md at "Prpriority_expr()" — do you see this ''? In code it is https://github.com/siberian-fast-food/alogger/blob/master/src/alog_control.erl#L76 . We also have forked edown to remove annoying header that duplicate first paragraph on all pages, but it's not so critical as loosing parts of docs.

**Comment by uwiger** [comment]
The duplicated heading has been eliminated in the latest version of edown.

**Comment by uwiger** [comment]
I see the problematic formatting - thanks. Much easier to fix with a concrete example. :)

**Comment by uwiger** [comment]
I pushed a fix to master. The alog_control.md file now renders like this: https://gist.github.com/c36a92afebff3c6d93bb

**Comment by si14** [comment]
Thanks a lot! Thought about fixing it by myself, but didn't have time. Can you please put a tag on this version (or maybe later, when you think it would be appropriate)? I'm trying to use only tagged versions in my production, so it would be nice to have one from edown :)

**Comment by uwiger** [comment]
Done: 0.2.9 is the new tag.

**Comment by si14** [comment]
Thanks again :)
