### ISSUE TITLE
top_level_readme - add option to hardcode branch used for GitHub links

### ISSUE THREAD

**Issue by norton** [esl/edown#8]
I'd like to have an option added to the top_level_readme to allow hardcoding of the branch (namely the "master" branch) used for GitHub links.  This would make pulling in changes from other branches to the master branch easier to manage.

https://github.com/norton/ubf/blob/master/rebar.config

%% Erlang edoc options
{edoc_opts, [{doclet, edown_doclet}
             , {src_path, ["src", "test"]}
             , {title, "Universal Binary Format"}
             , {top_level_readme, {"./README.md", "https://github.com/norton/ubf"}}
            ]}.

**Comment by uwiger** [comment]
I have added support for this in the latest commit
(https://github.com/esl/edown/commit/30a9f7867d615af45783235faa52742d11a9348e)

Let me know if this is what you wanted (or not).

**Comment by norton** [comment]
Yes, thank you.  This change works well.
